name: test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        node-version: ['16']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run CI test
        run: make ci-test
